### ISSUE TITLE
Cannot find module 'gulp-tinypng-compress'

### ISSUE THREAD

**Issue by connected** [stnvh/gulp-tinypng-compress#1]
I get an error "Cannot find module 'gulp-tinypng-compress'" when trying to run gulp task. NodeJs version v0.12.2. All other npm modules run fine.
I've installed module like it says in docs: 

``` sh
npm install --save-dev gulp-tinypng-compress
```

``` js
var gulp = require('gulp');
var tinypng = require('gulp-tinypng-compress');
```

Full error stack:

``` sh
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-tinypng-compress'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/andrew/Desktop/test/gulpfile.js:5:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Am I the only one with such error?

**Comment by stnvh** [comment]
I just tested and the install command seems to work. Make sure you're running it in the same directory as package.json (and usually your gulpfile, too), e.g:

```
project/
├── Gulpfile.js - Tasks
├── package.json - Dependencies
└── node_modules/ - created from running npm install
```

**Comment by stnvh** [comment]
Apologies, this was a separate issue where the index.js file wasn't being published. `1.1.1` fixes the issue.
